In [5]:
import os
import sys

# Add the Scripts directory to the PATH
os.environ['PATH'] = os.environ['PATH'] + ';C:\\Users\\anjal\\anaconda3\\Scripts'

# Verify the PATH has been updated
print(os.environ['PATH'])

# Now you should be able to run pip commands
!pip install tensorflow

C:\Users\anjal\anaconda3;C:\Users\anjal\anaconda3\Library\mingw-w64\bin;C:\Users\anjal\anaconda3\Library\usr\bin;C:\Users\anjal\anaconda3\Library\bin;C:\Users\anjal\anaconda3\Scripts;C:\Users\anjal\anaconda3\bin;C:\Users\anjal\anaconda3\condabin;C:\Users\anjal\anaconda3;C:\Users\anjal\anaconda3\Library\mingw-w64\bin;C:\Users\anjal\anaconda3\Library\usr\bin;C:\Users\anjal\anaconda3\Library\bin;C:\Users\anjal\anaconda3\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\MinGW\bin;C:\Program Files\CodeBlocks\MinGW\bin;C:\Program Files\Cloudflare\Cloudflare WARP;C:\Program Files\nodejs;C:\Users\anjal\AppData\Local\Microsoft\WindowsApps;C:\Users\anjal\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\anjal\AppData\Roaming\npm;C:\Users\anjal\anaconda3\Scripts


In [15]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.datasets import cifar10

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Reshape the data to be 2D
x_train = x_train.reshape((x_train.shape[0], -1))
x_test = x_test.reshape((x_test.shape[0], -1))

# Normalize the data
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
from sklearn.decomposition import PCA

# Apply PCA to the dataset
pca = PCA()
x_train_pca = pca.fit_transform(x_train)
x_test_pca = pca.transform(x_test)

# Get the eigenvalues and eigenvectors
eigenvalues = pca.explained_variance_
eigenvectors = pca.components_

# Compute the covariance matrix
covariance_matrix = np.cov(x_train.T)

# Print the eigenvalues, eigenvectors, and covariance matrix
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)
print("Covariance Matrix:")
print(covariance_matrix)

Eigenvalues:
[8.27004984e+02 3.49308855e+02 2.20112108e+02 ... 2.42349805e-05
 2.25321319e-05 2.24272605e-05]
Eigenvectors:
[[ 0.02221032  0.0234908   0.02368279 ...  0.01715567  0.01872997
   0.02005544]
 [-0.01677011 -0.01842545 -0.0190341  ...  0.01903027  0.01853711
   0.01632767]
 [-0.01833765 -0.0164207  -0.01132936 ... -0.02421813 -0.02241451
  -0.01675786]
 ...
 [-0.00263111  0.00348206 -0.00076102 ...  0.00156326 -0.00158543
   0.00026934]
 [ 0.00642339 -0.01161699  0.00551695 ...  0.00027251  0.00090381
  -0.00103491]
 [ 0.01162382 -0.01824903  0.00702637 ... -0.0017412   0.00138725
   0.00048463]]
Covariance Matrix:
[[1.00002    0.94197014 0.83712145 ... 0.34637163 0.3345564  0.32811162]
 [0.94197014 1.00002    0.92817584 ... 0.30851261 0.35240016 0.35488688]
 [0.83712145 0.92817584 1.00002    ... 0.25538166 0.30722361 0.38748167]
 ...
 [0.34637163 0.30851261 0.25538166 ... 1.00002    0.93251789 0.82315085]
 [0.3345564  0.35240016 0.30722361 ... 0.93251789 1.00002    0.90486

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Split the training set into a smaller training set and validation set
x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(x_train_pca, y_train, test_size=0.2, random_state=42)

print(f"Training data shape: {x_train_split.shape}, Validation data shape: {x_val_split.shape}")

# Train the RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(x_train_split, y_train_split.ravel())

print("Training complete")

# Make predictions on the validation set
y_val_pred = clf.predict(x_val_split)
val_accuracy = accuracy_score(y_val_split, y_val_pred)

print(f"Validation Accuracy: {val_accuracy:.4f}")

Training data shape: (40000, 3072), Validation data shape: (10000, 3072)
Training complete
Validation Accuracy: 0.3025


In [19]:
# Make predictions on the test set
y_test_pred = clf.predict(x_test_pca)

# Define class names
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# Convert numerical predictions to class names
y_test_pred_class_names = [class_names[pred] for pred in y_test_pred]

# Save predictions to a CSV file without headers
import pandas as pd

predictions_df = pd.DataFrame(y_test_pred_class_names)
predictions_df.to_csv('predictions.csv', index=False, header=False)